INSERT INTO SAMPLES (DESCRIPTION, SAMPLE_ID) VALUES ('MRSA', 1);
INSERT INTO SAMPLES (DESCRIPTION, SAMPLE_ID) VALUES ('ILA',  2);
INSERT INTO SAMPLES (DESCRIPTION, SAMPLE_ID) VALUES ('VOFF', 3);
INSERT INTO SAMPLES (DESCRIPTION, SAMPLE_ID) VALUES ('BJEFF',4);
